// [Hinglish, English]. Hinglish is the default voice.
import type { Festival, Maker, UiLang } from "./types";

type Line = readonly [string, string];

export const COPY = {
  brand: ["Yaadon Ki Rasoi", "Yaadon Ki Rasoi"],
  tagline: ["Bachpan ke swaad ka Shazam.", "Shazam for the taste of your childhood."],
  entry1: ["Diwali aa rahi hai.", "Diwali is coming."],
  entry2: ["Yaad hai… Nani ke ghar ki woh khushboo?", "Remember that smell from Nani's house?"],
  entry3: ["Naam yaad nahi? Koi baat nahi. Bas batao kaisa tha — hum dhoondh lenge.", "Can't remember the name? Just describe it — we'll find it."],
  remember: ["Haan, yaad hai", "Yes, I remember"],
  sound: ["Awaaz", "Sound"],
  soundOn: ["Awaaz chalu", "Sound on"],
  soundOff: ["Awaaz band", "Sound off"],
  language: ["Bhasha", "Language"],

  describeTitle: ["Batao… kya yaad aa raha hai?", "Tell me… what comes to mind?"],
  describeHelp: ["Jaise yaad hai waise likho — Hinglish, हिन्दी, English, ya kisi bhi bhasha mein.", "Write it the way you remember it — any language, any script."],
  ex1: ["Diwali pe Nani ke ghar gol-gol, upar til, gud ki meethi khushboo, tel mein talti thi…", "At Nani's every Diwali — round, sesame on top, smelled of jaggery, fried in oil…"],
  ex2: ["Dadi kuch bhara hua banati thi, andar khoya, kinare gundhe hue, ghee mein tala…", "Dadi made something stuffed with khoya, crimped edges, fried in ghee…"],
  ex3: ["Aai ki spiral wali kurkuri namkeen, chawal aur besan ki…", "Mom's crunchy spiral snack of rice and gram flour…"],
  memoryLabel: ["Aapki yaad", "Your memory"],
  senses: ["Yaad jagane ke liye", "Nudge your memory"],
  senseSmell: ["Khushboo", "Smell"],
  senseTaste: ["Swaad", "Taste"],
  senseSound: ["Awaaz", "Sound"],
  senseColour: ["Rang", "Colour"],
  senseShape: ["Shakal", "Shape"],
  senseSmellIns: ["Khushboo thi ", "It smelled of "],
  senseTasteIns: ["Swaad tha ", "It tasted "],
  senseSoundIns: ["Banate waqt awaaz aati thi ", "While cooking it sounded like "],
  senseColourIns: ["Rang tha ", "It was coloured "],
  senseShapeIns: ["Shakal thi ", "It was shaped "],
  makerOther: ["Koi aur", "Someone else"],
  makerQ: ["Kaun banata tha?", "Who made it?"],
  regionQ: ["Kahan manate the?", "Where did you celebrate?"],
  regionAny: ["Pata nahi / bataana nahi", "Not sure / prefer not to say"],
  cityQ: ["Aap abhi kis shehar mein ho?", "Which city are you in now?"],
  cityHelp: ["Aas-paas ki purani dukaanein aur Nani ke ghar ki doori ke liye.", "For old shops near you, and the distance to Nani's home."],
  cityNone: ["Abhi nahi", "Skip for now"],
  useLocation: ["Meri location lo", "Use my location"],
  myLocation: ["Meri location", "My location"],
  locating: ["Dhoondh rahe hain…", "Locating…"],
  locationDenied: ["Location nahi mili — list se shehar chuno.", "Couldn't get your location — pick a city instead."],
  remembered: ["Woh ab hamare saath nahi hain 🕯", "They're no longer with us 🕯"],
  rememberedHelp: ["Hum har baat narmi se kahenge.", "We'll keep everything gentle."],
  find: ["Dhoondho meri yaad", "Find my memory"],
  tooShort: ["Thoda aur batao — kam se kam ek line.", "Tell us a little more — at least a line."],
  trimmed: ["Lambi yaad! Pehle 600 akshar hi bheje jaayenge.", "Long memory! Only the first 600 characters will be sent."],
  charsLeft: ["{n} akshar baaki", "{n} characters left"],
  more: ["Aur batana hai?", "More details"],

  theatre: ["{maker} ki rasoi mein jhaank rahe hain…", "Peeking into {maker}'s kitchen…"],
  theatreGentle: ["Unki rasoi ki yaadon mein jhaank rahe hain…", "Looking back into their kitchen…"],
  st_parse: ["Aapke shabd sun liye", "Listened to your words"],
  st_retrieve: ["Google par recipes padh rahe hain", "Reading recipes on Google"],
  st_retrieveDone: ["{n} pages padh liye", "Read {n} pages"],
  st_extract: ["Naam chhaant rahe hain", "Picking out names"],
  st_extractDone: ["{n} naam mile, sab ke saboot ke saath", "{n} names found, each with proof"],
  st_photos: ["Tasveerein milaa rahe hain", "Matching photos"],
  st_aliases: ["Naksha dekh rahe hain", "Reading the map of names"],
  st_heartbeat: ["Purani Diwaliyan gin rahe hain", "Counting past Diwalis"],
  st_steps: ["Video mein vidhi sun rahe hain", "Listening to a recipe video"],
  st_shops: ["Purani dukaanein dhoondh rahe hain", "Looking for old shops"],
  reading: ["Padh rahe hain", "Reading"],
  words: ["Aapke shabd", "Your words"],

  recordedTitle: ["Record ki hui khoj", "Recorded investigation"],
  recorded_replay: ["Demo mode: koi API key nahi hai, isliye yeh {date} ko live SerpApi se record ki gayi asli khoj hai — milti-julti yaad ke liye.", "Demo mode: no API key, so this is a real investigation recorded from live SerpApi on {date}, for a similar memory."],
  recorded_budget: ["Aaj ki rasoi band hai — yeh {date} ki record ki hui asli khoj hai, milti-julti yaad ke liye.", "Today's kitchen is closed — this is a real investigation recorded on {date}, for a similar memory."],
  recorded_rate: ["Aaj aapki live khojein poori ho gayi — yeh {date} ki record ki hui khoj hai.", "You've used today's live searches — this one was recorded on {date}."],
  recorded_badkey: ["Aapki SerpApi key nahi chali — isliye {date} ki record ki hui khoj dikha rahe hain. 🔑 se key dobara check karo.", "Your SerpApi key didn't work, so this is a search recorded on {date}. Re-check the key under 🔑."],
  recorded_ownbudget: ["Aapki SerpApi key ki khojein khatam ho gayi — yeh {date} ki record ki hui khoj hai.", "Your SerpApi key is out of searches — this one was recorded on {date}."],
  recorded_serpapi: ["Search abhi jawab nahi de raha — yeh {date} ki record ki hui khoj hai.", "Search isn't responding right now — this one was recorded on {date}."],
  recordedSeed: ["Record ki gayi yaad", "Recorded memory"],

  confirmTitle: ["Kya yehi hai?", "Is this it?"],
  confirmHelp: ["Daayein swipe = haan, baayein = nahi. Ya neeche ke button dabao.", "Swipe right for yes, left for no — or use the buttons."],
  yes: ["Yehi hai!", "That's it!"],
  no: ["Nahi", "No"],
  noneOfThese: ["Koi nahi? Aur batao", "None of these? Tell us more"],
  why: ["Milta hai: {m}", "Matches: {m}"],
  seenOn: ["{n} sites par dekha", "seen on {n} sites"],
  alsoCalled: ["Ise yeh bhi kehte hain", "Also called"],
  photoFrom: ["Tasveer", "Photo"],
  cardOf: ["{i} / {n}", "{i} of {n}"],

  q_cook: ["Kaise banta tha?", "How was it cooked?"],
  q_shape: ["Shakal kaisi thi?", "What shape was it?"],
  q_base: ["Kis cheez se banta tha?", "What was it made of?"],
  q_taste: ["Meetha ya namkeen?", "Sweet or savoury?"],
  "o_deep fried": ["Tala hua", "Deep fried"],
  o_roasted: ["Bhuna / seka hua", "Roasted"],
  o_steamed: ["Bhaap mein", "Steamed"],
  "o_sugar syrup": ["Chashni mein dooba", "Soaked in syrup"],
  o_round: ["Gol", "Round"],
  o_spiral: ["Chakri jaisa", "Spiral"],
  o_stuffed: ["Andar bharawan", "Stuffed"],
  o_flat: ["Chapta", "Flat"],
  "o_rice flour": ["Chawal", "Rice"],
  "o_gram flour": ["Besan", "Gram flour"],
  o_semolina: ["Suji", "Semolina"],
  "o_wheat flour": ["Aata / maida", "Wheat flour"],
  o_coconut: ["Nariyal", "Coconut"],
  o_sweet: ["Meetha", "Sweet"],
  o_savory: ["Namkeen", "Savoury"],
  dontKnow: ["Pata nahi", "Not sure"],
  noMatch: ["Abhi pakka naam nahi mila.", "We couldn't pin down a name yet."],
  noMatchHelp: ["Shayad inmein se koi ho — ya thoda alag shabdon mein phir se likho.", "Maybe it's one of these — or try describing it a little differently."],
  tryAgain: ["Phir se likho", "Describe again"],

  found: ["Mil gaya.", "Found it."],
  heroOf: ["{maker} ka {dish}", "{maker}'s {dish}"],
  heroGentle: ["{maker} ki yaad mein — {dish}", "In {maker}'s memory — {dish}"],
  namesChip: ["Ek swaad, {n} naam", "One taste, {n} names"],
  namesTitle: ["Ek swaad, {n} naam", "One taste, {n} names"],
  namesSub: ["Har rajya mein Google par sabse zyada khoja gaya naam.", "The name each state searches most on Google."],
  mapNote: ["Bharat ka naksha aadhikarik seemaon ke saath (svg-maps, CC BY 4.0). Pin andaaze se.", "India's outline as officially depicted (svg-maps, CC BY 4.0). Pins are approximate."],
  listenAll: ["Desh bhar ki naaniyon se suno", "Hear grandmothers across India"],
  stopVoice: ["Ruko", "Stop"],
  aiVoice: ["AI awaaz (Cartesia) — asli naani nahi", "AI voice (Cartesia) — not a real grandmother"],
  tapState: ["Kisi rajya ke diye ko chhuo — wahan ki naani bolegi", "Tap a state — its grandmother will speak"],
  meaning: ["Matlab", "Meaning"],
  noVoice: ["Is awaaz ki recording abhi nahi hai.", "No recording for this voice yet."],
  accuracy: ["Aapki location, ±{m} m tak sahi", "Your location, accurate to ±{m} m"],
  pickOnMap: ["Map par chuno", "Pick on map"],
  pickedOnMap: ["Map par chuni jagah", "Spot picked on map"],
  tapMapHint: ["Gaon ya mohalla list mein nahi? Map par us jagah ko chhuo.", "Village not in the list? Tap the spot on the map."],
  searchingPlaces: ["Gaon-shehar dhoondh rahe hain…", "Looking for towns and villages…"],
  osmCredit: ["Jagah ki khoj: © OpenStreetMap", "Place search: © OpenStreetMap contributors"],
  keyBtn: ["Apni key", "Your key"],
  keyLive: ["Live", "Live"],
  keyTitle: ["Apni SerpApi key lagao", "Use your own SerpApi key"],
  keyWhy: ["Yeh site live khoj aapki apni free SerpApi key se chalati hai. Bina key ke bhi record ki hui asli khojein chalti hain.", "This site runs live searches with your own free SerpApi key. Without one, you still get real recorded searches."],
  keyStep1: ["serpapi.com par free account banao — har mahine 250 khojein free.", "Create a free account at serpapi.com — 250 searches a month, free."],
  keyStep2: ["Dashboard mein 'Your Private API Key' copy karo.", "In the dashboard, copy 'Your Private API Key'."],
  keyStep3: ["Yahan paste karke 'Check karke lagao' dabao.", "Paste it here and press 'Check & save'."],
  keyCost: ["Ek poori khoj lagbhag 10–12 credits leti hai; dobara wahi khoj free (cache).", "One full search uses about 10–12 credits; repeating it is free (cached)."],
  keyPrivacy: ["Aapki key sirf aapke browser mein save hoti hai. Hum ise kabhi save, log ya share nahi karte — har khoj par yeh sirf SerpApi tak pahunchne ke liye hamare server se guzarti hai, bas.", "Your key is saved only in your browser. We never store, log or share it — on each search it only passes through our server to reach SerpApi, nothing more."],
  keyLabel: ["SerpApi key", "SerpApi key"],
  keyCheck: ["Check karke lagao", "Check & save"],
  keyChecking: ["Check kar rahe hain…", "Checking…"],
  keyOk: ["Lag gayi ✓ — {left} khojein baaki ({plan})", "Saved ✓ — {left} searches left ({plan})"],
  keyBad: ["Yeh key nahi chali. Dobara copy karke dekho.", "That key didn't work. Copy it again and retry."],
  keyFormat: ["Key 64 akshar ki hoti hai (0-9, a-f).", "A key is 64 characters (0-9, a-f)."],
  keyRemove: ["Key hatao", "Remove key"],
  keyBanner: ["Abhi record ki hui asli khojein chalengi. Apni yaad live dhoondhne ke liye apni free SerpApi key lagao →", "Right now you'll see real recorded searches. To search your own memory live, add your free SerpApi key →"],
  showShops: ["Dukaanein dikhao", "Show shops"],
  keepTitle: ["Yaad sambhalo, sabko dikhao", "Keep it. Share it."],
  keepSub: ["Link na chale toh bhi — card ya PDF download karke kahin bhi bhejo.", "Even without a link — download the card or a PDF and send it anywhere."],
  dlImage: ["Card download karo", "Download card"],
  dlPdf: ["PDF download karo", "Download PDF"],
  preparing: ["Bana rahe hain…", "Preparing…"],
  downloaded: ["Download ho gaya ✓", "Downloaded ✓"],
  shareOn: ["Yahan share karo", "Share on"],
  igHint: ["Card save ho gaya aur caption copy — Instagram Story ya Post mein daal do.", "Card saved and caption copied — add it to an Instagram Story or Post."],
  moreApps: ["Aur apps", "More apps"],
  cardMaker: ["{maker} ka…", "{maker}'s…"],
  cardInMemory: ["{maker} ki yaad mein…", "In {maker}'s memory…"],
  cardNames: ["Ek swaad, {n} naam", "One taste, {n} names"],
  cardFooter: ["Apni yaad dhoondho →", "Find your own memory →"],
  cardDistance: ["{km} km door", "{km} km away"],
  shareCaption: ["Maine {maker} ka {dish} dhoondh liya 🪔 Ek swaad, desh bhar mein kai naam. Tum bhi apni bachpan ki yaad dhoondho:", "I found {maker}'s {dish} 🪔 One taste, many names across India. Find your own childhood memory:"],
  shareTitle: ["{maker} ka {dish} — Yaadon Ki Rasoi", "{maker}'s {dish} — Yaadon Ki Rasoi"],
  recipeSheet: ["Parivaar ki recipe", "The family recipe"],
  cardPulse: ["Aap akele nahi hain — {y} mein se {f} Diwali par India ne isi ko dhoondha.", "You're not alone — in {f} of {y} Diwalis, India searched for this."],
  navHistory: ["Meri yaadein", "My memories"],
  historyTitle: ["Meri yaadein", "My memories"],
  historySub: ["Har dhoondhi hui yaad sirf isi browser mein save hoti hai — hamare server par kuch nahi.", "Every memory you find is saved only in this browser — nothing on our server."],
  historyEmpty: ["Abhi tak koi yaad nahi dhoondhi.", "You haven't found a memory yet."],
  historyOpen: ["Kholo", "Open"],
  historyDelete: ["Hatao", "Delete"],
  historyBack: ["← Saari yaadein", "← All memories"],
  historyMissing: ["Yeh yaad is browser mein nahi mili.", "This memory isn't saved in this browser."],
  savedHistory: ["Meri yaadein mein save ho gaya ✓", "Saved to My memories ✓"],
  stillNeeded: ["Abhi baaki: {items}", "Still needed: {items}"],
  needMemory: ["thodi aur yaad (kam se kam ek line)", "a little more memory (at least a line)"],
  needHome: ["{maker} ka ghar — list se chuno", "{maker}'s home — pick from the list"],
  needYourCity: ["aapka shehar — list se chuno", "your city — pick from the list"],
  aiThinking: ["Chrome ka on-device AI samajh raha hai…", "Chrome's on-device AI is reading it…"],
  aiUsed: ["Chrome ke on-device AI ne samjha", "Understood by Chrome's on-device AI"],
  homeQ: ["{maker} ka ghar kahan tha?", "Where was {maker}'s home?"],
  homeHelp: ["Gaon, qasba, shehar — kuch bhi likho, ya map par chuno. Aakhir mein ek chhoti si baat dikhayenge.", "Any village, town or city — or pick it on the map. We'll show you something at the end."],
  homePh: ["Jaise: Tekari, Gaya", "e.g. Tekari, Gaya"],
  homeOf: ["{maker} ka ghar", "{maker}'s home"],
  youLabel: ["Aap", "You"],
  dooriEyebrow: ["Ghar ki doori", "The distance home"],
  dooriTitle: ["{maker} ka ghar {km} km door hai.", "{maker}'s home is {km} km away."],
  dooriNear: ["{maker} ka ghar bas {km} km door hai.", "{maker}'s home is just {km} km away."],
  dooriSame: ["Aap {maker} ke ghar ke paas hi ho.", "You're right near {maker}'s home."],
  dooriSub: ["Par yeh swaad ab bas ek seeti door hai. 🪔", "But this taste is now just one whistle away. 🪔"],
  dooriSubNear: ["Is Diwali, ek chakkar laga aao? 🪔", "Maybe drop by this Diwali? 🪔"],
  dooriGentle: ["Ghar door hai, par yaadein yahin hain — aapke paas. 🕯", "Home is far, but the memories are right here with you. 🕯"],
  dooriAsk: ["Doori dekhne ke liye bas do jagah batao", "Tell us two places to see the distance"],
  listAlt: ["Rajya-vaar soochi", "State-by-state list"],
  share: ["{n}% hissa", "{n}% share"],
  noNames: ["Is naam ke liye rajya-vaar data kam hai.", "Not enough state-level search data for this name."],
  heartTitle: ["Aap akele nahi hain.", "You're not alone."],
  heartSub: ["India har saal isi ko dhoondhta hai — {y} mein se {f} saal sabse zyada khoj Diwali ke mausam (Oct–Nov) mein.", "India looks for this every year — in {f} of {y} years the peak fell in Diwali season (Oct–Nov)."],
  heartCaption: ["Google Trends: India mein relative search interest, 2004 → aaj (0–100 index, asli ginti nahi).", "Google Trends: relative search interest in India, 2004 → today (0–100 index, not absolute counts)."],
  heartAlt: ["'{term}' ki khoj ka graph: {peaks}", "Search interest chart for '{term}': {peaks}"],
  stepsTitle: ["Kaise banta tha", "How it was made"],
  stepsAi: ["AI ne {channel} ke video ke transcript se saaraansh banaya — video zaroor dekhiye.", "Summarised by AI from {channel}'s video transcript — always watch the video."],
  stepsVerbatim: ["{channel} ke video se seedhe shabd, samay ke saath.", "Exact lines from {channel}'s video, with timestamps."],
  stepsNone: ["Is video ka transcript nahi mila — seedha video dekhiye.", "No transcript for this video — watch it directly."],
  almari: ["{maker} ki almari se", "From {maker}'s shelf"],
  watchAt: ["{t} par dekho", "Watch at {t}"],
  playVideo: ["Video chalao", "Play video"],
  shopsTitle: ["Aaj bhi zinda hai", "Still alive today"],
  shopsSub: ["{city} mein, 15 km ke andar", "In {city}, within 15 km"],
  mentions: ["{n} reviews mein iska zikr", "mentioned in {n} reviews"],
  call: ["Call karo", "Call"],
  directions: ["Raasta", "Directions"],
  reviewer: ["Google Maps par ek reviewer", "A reviewer on Google Maps"],
  noShops: ["Paas mein nahi mili — vidhi try karo, ghar jaisa banega.", "None nearby — try the recipe, it'll taste like home."],
  needCity: ["Aas-paas ki dukaanein dekhne ke liye shehar chuno", "Pick a city to see shops near you"],
  sceneFail: ["Yeh hissa abhi nahi mil paaya.", "Couldn't load this part right now."],
  km: ["{n} km", "{n} km"],


  drawer: ["Rasoi ke peeche", "Under the hood"],
  drawerSub: ["Is khoj mein SerpApi ki har call — asli, live.", "Every SerpApi call in this investigation — real and live."],
  ingredients: ["Saamagri", "Ingredients"],
  credits: ["Credits: {c} · Cache/replay: {h}", "Credits: {c} · Cache/replay: {h}"],
  close: ["Band karo", "Close"],
  live: ["live", "live"],
  cache: ["cache", "cache"],
  replay: ["recorded", "recorded"],
  recordedOn: ["Recorded {date}", "Recorded {date}"],
  liveNow: ["{engine} · live", "{engine} · live"],

  namesAcross: ["Desh bhar mein iske naam", "Its names across India"],
  copyLink: ["Link copy karo", "Copy link"],
  copied: ["Copy ho gaya ✓", "Copied ✓"],
  error: ["Kuch gadbad ho gayi. Phir se koshish karein.", "Something went wrong. Please try again."],
  offline: ["Aap offline hain — net aate hi phir koshish karein.", "You're offline — try again when you're back."],
  back: ["Wapas", "Back"],
  newSearch: ["Nayi yaad", "New memory"],
  skipToContent: ["Seedha content par jaayein", "Skip to content"],
  invGone: ["Yeh khoj purani ho gayi — ek baar phir se likho.", "This search has expired — please describe it again."],
  maybeThis: ["Shayad yeh?", "Maybe one of these?"],
  noRecordings: ["Abhi koi record ki hui khoj nahi hai — README dekhiye.", "No recorded investigations yet — see the README."],
  stillness: ["…", "…"],
  footer: ["SerpApi se bana · khulla source", "Built on SerpApi · open source"],
} as const satisfies Record<string, Line>;

export type CopyKey = keyof typeof COPY;
const IDX: Record<UiLang, number> = { hinglish: 0, en: 1 };

export function t(lang: UiLang, key: CopyKey, vars?: Record<string, string | number>) {
  let s: string = COPY[key][IDX[lang]];
  if (vars) for (const [k, v] of Object.entries(vars)) s = s.split(`{${k}}`).join(String(v));
  return s;
}

export const MAKER_LABEL: Record<Maker, Line> = {
  nani: ["Nani", "Nani"],
  dadi: ["Dadi", "Dadi"],
  maa: ["Maa", "Mom"],
  papa: ["Papa", "Dad"],
  other: ["Ghar", "home"],
};

export const FESTIVAL_LABEL: Record<Festival, Line> = {
  diwali: ["Diwali", "Diwali"],
  dhanteras: ["Dhanteras", "Dhanteras"],
  "bhai-dooj": ["Bhai Dooj", "Bhai Dooj"],
  chhath: ["Chhath", "Chhath"],
  "durga-puja": ["Durga Puja", "Durga Puja"],
  navratri: ["Navratri", "Navratri"],
  "kali-puja": ["Kali Puja", "Kali Puja"],
  pongal: ["Pongal", "Pongal"],
  onam: ["Onam", "Onam"],
  lohri: ["Lohri", "Lohri"],
  holi: ["Holi", "Holi"],
  eid: ["Eid", "Eid"],
  christmas: ["Christmas", "Christmas"],
  other: ["Koi aur", "Another"],
};


export const pick = (lang: UiLang, line: Line) => line[IDX[lang]];
